title: <span style="font-family: monospace;">astro* bot;</span>
description: <span style="font-family: monospace;">astro* bot;</span> is a simple and easy-to-use astronomical telegram bot.
show_downloads: false
google_analytics: G-K3DN3XKBC3
theme: jekyll-theme-cayman