title: >
    <span style="font-family: monospace;">astro* bot;</span>
description: >
    Your starting point(er) to the fascinating astronomy!
show_downloads: false
google_analytics: G-K3DN3XKBC3
theme: jekyll-theme-cayman